=== saadmaz/IIT-L4-Year1/Web Design and Development - 4COSC011C.2/Tutorials/Week 10 - XML and DTD Lecture Exercise/Employee.dtd
<!DOCTYPE employeelist
[
<!ELEMENT employeelist (employee+)>
<!ELEMENT employee(name,address,mobile*)>
<!ELEMENT name(firstName, secondName?)>
<!ELEMENT firstName (#PCADATA)>
<!ELEMENT secondName(#PCADATA)>
<!ELEMENT address (#PCADATA)>
<!ELEMENT mobile (#PCADATA)>

]>

=== saadmaz/IIT-L4-Year1/Web Design and Development - 4COSC011C.2/Tutorials/Week 10 - XML and DTD Lecture Exercise/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE employeelist SYSTEM "Employee.dtd">-->
<!DOCTYPE employeelist
[
<!ELEMENT employeelist (employee+)>
<!ELEMENT employee (name,address,mobile*)>
<!ELEMENT name (firstName,secondName?)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT secondName (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

]>


<employeelist>
<employee>
<name>
<firstName>
Peter
</firstName>
<secondName>
Ann
</secondName>
</name>
<address>
UK street
</address>
<mobile>
98766
</mobile>
</employee>
<employee>

<name>
<firstName>
John
</firstName>
</name>
<address>
UK street
</address>
</employee>
</employeelist>
